### PR TITLE
Update upstream

### PR DESCRIPTION
**Pull request by pikulmar**

### CODE REVIEW

**Comment by pikulmar** [comment]
@fortum-vaanavil please add yourself as reviewer, I apparently lack permission to do so...

**Comment by fortum-vaanavil** [comment]
I apparently lack permissions too

**Review by fortum-vaanavil — APPROVED** [review]

**Comment by pikulmar** [comment]
Who can merge this??? Is there any interest in merging this? Seems that actually do not / no longer use this repository.

**Review by fortum-vaanavil — APPROVED** [review]

**Comment by fortum-vaanavil** [comment]
Not sure where we're using this

**Comment by pikulmar** [comment]
@alau @saikonen @ferras Please feel free to re-open and merge this PR if the change is interesting for you.

**Pull request closed without merging**
